CREATE TABLE IF NOT EXISTS NIVEL(
    ID INT NOT NULL AUTO_INCREMENT,
    NOMBRE TEXT NOT NULL,
    FECHA_CREACION TEXT NOT NULL,
    DATALEVEL LONGTEXT NOT NULL,
    CORREO VARCHAR(200) NOT NULL,
    FOREIGN KEY CORREO REFERENCES USUARIOS (CORREO)
);