CREATE TABLE IF NOT EXISTS INFORMACION_USUARIO(
    CORREO VARCHAR(200) NOT NULL,
    NOMBRE TEXT NOT NULL,
    TELEFONO VARCHAR(12),
    FECHA_CREACION TEXT,
    FOREIGN KEY (CORREO) REFERENCES USUARIO (CORREO)
);